@startuml
!include ../exasol.skin

Select *-- "*" Field
Select *-- "0..1" FromClause
Select *-- "0..1" LimitClause
Select *-- "0..1" WhereClause
FromClause *-- "*" Table
FromClause *-- "*" Join
WhereClause *-- BooleanExpression
BooleanExpression *-- "0..1" BooleanExpression
@enduml